FROM python:3.9

WORKDIR /app
# misspelt app as appp

COPY app.py /app
# misspelt app.py as appy.py

RUN pip install flask netiface

EXPOSE "eight thousand"
# port is a numeric value

CMD ["pythn", "app.py"]
